In [1]:
pip install pandas

Requirement already satisfied: pandas in c:\mlstart\day2\venv\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.22.4 in c:\mlstart\day2\venv\lib\site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\mlstart\day2\venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\mlstart\day2\venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\mlstart\day2\venv\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\mlstart\day2\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [6]:
import pandas as pd
df=pd.read_csv('tata_data.csv')

In [7]:
df.head(5)

,Price,Close,High,Low,Open,Volume
0,Ticker,TATACONSUM.NS,TATACONSUM.NS,TATACONSUM.NS,TATACONSUM.NS,TATACONSUM.NS
1,Date,NaN,NaN,NaN,NaN,NaN
2,1/1/2015,132.6536255,133.5778903,132.3455462,132.8736879,535692
3,1/2/2015,134.2380676,134.8542397,132.5215835,132.8296629,2043127
4,1/5/2015,134.6341858,135.9985755,133.4898585,133.4898585,1873161

In [8]:
df.tail()

           Price        Close         High          Low         Open   Volume
2463  12/23/2024  896.1085815  899.3346717  883.4523817  888.3659773  1054695
2464  12/24/2024   900.625061  906.2335187  890.2023086   898.292374  1038280
2465  12/26/2024  894.3218384  904.6452906  891.9890907  901.3199603   595956
2466  12/27/2024  901.2703247  904.6949556  892.3861567  895.3640861   870974
2467  12/30/2024  896.8530273  905.2904936  892.0883527  901.2703012  1830048

In [9]:
print(df['Price'])

0           Ticker
1             Date
2         1/1/2015
3         1/2/2015
4         1/5/2015
           ...
2463    12/23/2024
2464    12/24/2024
2465    12/26/2024
2466    12/27/2024
2467    12/30/2024
Name: Price, Length: 2468, dtype: object

In [10]:
df['Open']

0       TATACONSUM.NS
1                 NaN
2         132.8736879
3         132.8296629
4         133.4898585
            ...
2463      888.3659773
2464       898.292374
2465      901.3199603
2466      895.3640861
2467      901.2703012
Name: Open, Length: 2468, dtype: object

In [11]:
type(df['Open'])

pandas.core.series.Series

In [13]:
df.loc[:, 'Open']

0       TATACONSUM.NS
1                 NaN
2         132.8736879
3         132.8296629
4         133.4898585
            ...
2463      888.3659773
2464       898.292374
2465      901.3199603
2466      895.3640861
2467      901.2703012
Name: Open, Length: 2468, dtype: object

In [16]:
df.iloc[:,0]

0           Ticker
1             Date
2         1/1/2015
3         1/2/2015
4         1/5/2015
           ...
2463    12/23/2024
2464    12/24/2024
2465    12/26/2024
2466    12/27/2024
2467    12/30/2024
Name: Price, Length: 2468, dtype: object

In [24]:
df.iloc[:10,:4]

       Price          Close           High            Low
0     Ticker  TATACONSUM.NS  TATACONSUM.NS  TATACONSUM.NS
1       Date            NaN            NaN            NaN
2   1/1/2015    132.6536255    133.5778903    132.3455462
3   1/2/2015    134.2380676    134.8542397    132.5215835
4   1/5/2015    134.6341858    135.9985755    133.4898585
5   1/6/2015    130.4089813    133.7539327    129.3966996
6   1/7/2015    130.6730499    131.3332371    128.5164411
7   1/8/2015    135.2943726     135.998575    131.5973266
8   1/9/2015    136.9668579    138.8153742    134.9422809
9  1/12/2015    138.5072937    139.6956227    136.6147488

In [27]:
df.iloc[2][2]

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_5532\870244984.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[2][2]

'133.5778903'

In [29]:
df.at[2,'Open']

'132.8736879'

In [30]:
df.iat[2,3]

'132.3455462'

In [31]:
data={
    "Name":["Priyanshu","Vibhav","Ashutosh"],
    "Age":[22,23,27],
    "heirarchy":["low","middle","high"] 
}
df=pd.DataFrame(data)
print(df)

        Name  Age heirarchy
0  Priyanshu   22       low
1     Vibhav   23    middle
2   Ashutosh   27      high

In [32]:
df['Salary']=[50000,40000,60000]

In [33]:
df

        Name  Age heirarchy  Salary
0  Priyanshu   22       low   50000
1     Vibhav   23    middle   40000
2   Ashutosh   27      high   60000

In [34]:
df.drop('Salary',axis=1)

        Name  Age heirarchy
0  Priyanshu   22       low
1     Vibhav   23    middle
2   Ashutosh   27      high

In [35]:
df

        Name  Age heirarchy  Salary
0  Priyanshu   22       low   50000
1     Vibhav   23    middle   40000
2   Ashutosh   27      high   60000

In [36]:
df.drop(0,inplace=True)

In [37]:
df

       Name  Age heirarchy  Salary
1    Vibhav   23    middle   40000
2  Ashutosh   27      high   60000

In [38]:
df.drop('Salary',axis=1)

       Name  Age heirarchy
1    Vibhav   23    middle
2  Ashutosh   27      high

In [39]:
df

       Name  Age heirarchy  Salary
1    Vibhav   23    middle   40000
2  Ashutosh   27      high   60000

In [40]:
df.drop('Salary',axis=1,inplace=True)

In [41]:
df

       Name  Age heirarchy
1    Vibhav   23    middle
2  Ashutosh   27      high

In [48]:
df.loc[len(df)]={
    'Name':'Priyanshu',
    'Age':22,
    'heirarchy':'low'
    }

In [49]:
df

        Name  Age heirarchy
1     Vibhav   23    middle
2   Ashutosh   27      high
0  Priyanshu   22       low
3  Priyanshu   22       low

In [50]:
df.drop(0,inplace=True)

In [51]:
df

        Name  Age heirarchy
1     Vibhav   23    middle
2   Ashutosh   27      high
3  Priyanshu   22       low

In [52]:
df['Qualities']=['Smartest','Bravest','Fighter']

In [53]:
df

        Name  Age heirarchy Qualities
1     Vibhav   23    middle  Smartest
2   Ashutosh   27      high   Bravest
3  Priyanshu   22       low   Fighter

In [55]:
df.drop([2,2],inplace=True)

In [56]:
df

        Name  Age heirarchy Qualities
1     Vibhav   23    middle  Smartest
3  Priyanshu   22       low   Fighter

In [58]:
df.loc[len(df)]={
    "Name":"Ashutosh",
    "Age":27,
    "heirarchy":"big"
}

In [59]:
df

        Name  Age heirarchy Qualities
1     Vibhav   23    middle  Smartest
3  Priyanshu   22       low   Fighter
2   Ashutosh   27       big       NaN

In [61]:
df.iloc[2,3]="Bravest"

In [62]:
df

        Name  Age heirarchy Qualities
1     Vibhav   23    middle  Smartest
3  Priyanshu   22       low   Fighter
2   Ashutosh   27       big   Bravest

In [63]:
df['Age']=df['Age']+1

In [64]:
df

        Name  Age heirarchy Qualities
1     Vibhav   24    middle  Smartest
3  Priyanshu   23       low   Fighter
2   Ashutosh   28       big   Bravest

In [65]:
df=pd.read_csv('tata_data.csv')
print("data types:\n",df.dtypes)

data types:
 Price     object
Close     object
High      object
Low       object
Open      object
Volume    object
dtype: object

In [66]:
print("Statistical Summary:\n",df.describe())

Statistical Summary:
              Price        Close        High          Low        Open   Volume
count         2468         2467        2467         2467        2467     2467
unique        2468         2286        2463         2464        2464     2463
top     12/30/2024  113.1391678  128.820765  242.1182762  108.781979  1154541
freq             1            4           2            2           2        2

In [69]:
data={
    "Name":["Priyanshu","Vibhav","Ashutosh"],
    "Age":[22,23,27],
    "heirarchy":["low","middle","high"] 
}
df=pd.DataFrame(data)
print(df)

        Name  Age heirarchy
0  Priyanshu   22       low
1     Vibhav   23    middle
2   Ashutosh   27      high

In [71]:
grouped=df.groupby('Name')['Age'].mean()

In [72]:
print("mean value by Name:\n",grouped)

mean value by Name:
 Name
Ashutosh     27.0
Priyanshu    22.0
Vibhav       23.0
Name: Age, dtype: float64

In [73]:
data = {
    "Name": ["Priyanshu","Priyanshu","Vibhav","Vibhav"],
    "Age": [22, 24, 23, 25]
}

df = pd.DataFrame(data)
print(df)

# print(df.groupby('Name')['Age'].mean())

        Name  Age
0  Priyanshu   22
1  Priyanshu   24
2     Vibhav   23
3     Vibhav   25

In [74]:
print(df.groupby('Name')['Age'].mean())

Name
Priyanshu    23.0
Vibhav       24.0
Name: Age, dtype: float64

In [75]:
df.dtypes

Name    object
Age      int64
dtype: object

In [78]:
df=pd.read_csv('tata_data.csv')
df.isnull()

      Price  Close   High    Low   Open  Volume
0     False  False  False  False  False   False
1     False   True   True   True   True    True
2     False  False  False  False  False   False
3     False  False  False  False  False   False
4     False  False  False  False  False   False
...     ...    ...    ...    ...    ...     ...
2463  False  False  False  False  False   False
2464  False  False  False  False  False   False
2465  False  False  False  False  False   False
2466  False  False  False  False  False   False
2467  False  False  False  False  False   False

[2468 rows x 6 columns]

In [80]:
df.isnull().any()

Price     False
Close      True
High       True
Low        True
Open       True
Volume     True
dtype: bool

In [81]:
df.isnull().any(axis=1)

0       False
1        True
2       False
3       False
4       False
        ...
2463    False
2464    False
2465    False
2466    False
2467    False
Length: 2468, dtype: bool

In [82]:
df.isnull().sum()

Price     0
Close     1
High      1
Low       1
Open      1
Volume    1
dtype: int64

In [83]:
df_filled=df.fillna(0)

In [84]:
df_filled

,Price,Close,High,Low,Open,Volume
0,Ticker,TATACONSUM.NS,TATACONSUM.NS,TATACONSUM.NS,TATACONSUM.NS,TATACONSUM.NS
1,Date,0,0,0,0,0
2,1/1/2015,132.6536255,133.5778903,132.3455462,132.8736879,535692
3,1/2/2015,134.2380676,134.8542397,132.5215835,132.8296629,2043127
4,1/5/2015,134.6341858,135.9985755,133.4898585,133.4898585,1873161
...,...,...,...,...,...,...
2463,12/23/2024,896.1085815,899.3346717,883.4523817,888.3659773,1054695
2464,12/24/2024,900.625061,906.2335187,890.2023086,898.292374,1038280
2465,12/26/2024,894.3218384,904.6452906,891.9890907,901.3199603,595956
2466,12/27/2024,901.2703247,904.6949556,892.3861567,895.3640861,870974
2467,12/30/2024,896.8530273,905.2904936,892.0883527,901.2703012,1830048

In [85]:
df.isnull().sum()

Price     0
Close     1
High      1
Low       1
Open      1
Volume    1
dtype: int64

In [87]:
data={
    "Name":["Priyanshu","Vibhav","Ashutosh"],
    "Age":[22,23,27],
    "heirarchy":["low","middle","high"] 
}
df=pd.DataFrame(data)
print(df)
df['number']=[20,11,1]

        Name  Age heirarchy
0  Priyanshu   22       low
1     Vibhav   23    middle
2   Ashutosh   27      high

In [88]:
df

        Name  Age heirarchy  number
0  Priyanshu   22       low      20
1     Vibhav   23    middle      11
2   Ashutosh   27      high       1

In [90]:
df.drop(index=df.index[2],columns=df.columns[3],inplace=True)

In [91]:
df

        Name  Age heirarchy
0  Priyanshu   22       low
1     Vibhav   23    middle

In [94]:
df['Number']=[20,23]
df.loc[len(df)]={
"Name":"Ashutosh",
"Age":28,
"heirarchy":"high"
}

In [95]:
df

        Name  Age heirarchy  Number
0  Priyanshu   22       low    20.0
1     Vibhav   23    middle    23.0
2   Ashutosh   28      high     NaN

In [96]:
df.isnull()

    Name    Age  heirarchy  Number
0  False  False      False   False
1  False  False      False   False
2  False  False      False    True

In [97]:
df.isnull().any()

Name         False
Age          False
heirarchy    False
Number        True
dtype: bool

In [98]:
df.isnull().any(axis=1)

0    False
1    False
2     True
dtype: bool

In [99]:
df['New_Number']=df['Number'].fillna(df['Age'].mean())

In [100]:
df

        Name  Age heirarchy  Number  New_Number
0  Priyanshu   22       low    20.0   20.000000
1     Vibhav   23    middle    23.0   23.000000
2   Ashutosh   28      high     NaN   24.333333

In [101]:
df.rename(columns={'Number':'value'})

        Name  Age heirarchy  value  New_Number
0  Priyanshu   22       low   20.0   20.000000
1     Vibhav   23    middle   23.0   23.000000
2   Ashutosh   28      high    NaN   24.333333

In [105]:
df['Value_new']=df['Number'].fillna(df['New_Number'].mean()).astype(int)

In [106]:
df

        Name  Age heirarchy  Number  New_Number  Value_new
0  Priyanshu   22       low    20.0   20.000000         20
1     Vibhav   23    middle    23.0   23.000000         23
2   Ashutosh   28      high     NaN   24.333333         22

In [107]:
df['mult']=df['Value_new'].apply(lambda x:x*2)

In [108]:
df

        Name  Age heirarchy  Number  New_Number  Value_new  mult
0  Priyanshu   22       low    20.0   20.000000         20    40
1     Vibhav   23    middle    23.0   23.000000         23    46
2   Ashutosh   28      high     NaN   24.333333         22    44

In [109]:
grouped_mean=df.groupby('Name')['Value_new'].mean()
print(grouped_mean)

Name
Ashutosh     22.0
Priyanshu    20.0
Vibhav       23.0
Name: Value_new, dtype: float64

In [111]:
grouped_sum=df.groupby(['Name','Value_new'])['mult'].sum()

In [112]:
print(grouped_sum)

Name       Value_new
Ashutosh   22           44
Priyanshu  20           40
Vibhav     23           46
Name: mult, dtype: int64

In [113]:
import pandas as pd

data = {
    "Department": ["IT", "IT", "HR", "HR", "Finance", "IT"],
    "Employee": ["A", "B", "C", "D", "E", "F"],
    "Salary": [50000, 60000, 40000, 45000, 70000, 55000],
    "Bonus": [5000, 6000, 3000, 3500, 7000, 5200]
}

df = pd.DataFrame(data)
print(df)

  Department Employee  Salary  Bonus
0         IT        A   50000   5000
1         IT        B   60000   6000
2         HR        C   40000   3000
3         HR        D   45000   3500
4    Finance        E   70000   7000
5         IT        F   55000   5200

In [114]:
grouped_mean=df.groupby('Department')['Salary'].mean()
print(grouped_mean)

Department
Finance    70000.0
HR         42500.0
IT         55000.0
Name: Salary, dtype: float64

In [115]:
df

  Department Employee  Salary  Bonus
0         IT        A   50000   5000
1         IT        B   60000   6000
2         HR        C   40000   3000
3         HR        D   45000   3500
4    Finance        E   70000   7000
5         IT        F   55000   5200

In [117]:
grouped_sum=df.groupby(['Department','Employee'])['Salary'].sum()
print(grouped_sum)

Department  Employee
Finance     E           70000
HR          C           40000
            D           45000
IT          A           50000
            B           60000
            F           55000
Name: Salary, dtype: int64

In [118]:
grouped_agg=df.groupby('Department')['Salary'].agg(['mean','sum','count'])
print(grouped_agg)

               mean     sum  count
Department
Finance     70000.0   70000      1
HR          42500.0   85000      2
IT          55000.0  165000      3

In [128]:
df1=pd.DataFrame({'key':['A','B','C'],
                  'Value1':[1,2,3]
                  })
df2=pd.DataFrame({'key':['A','B','D'],
                  'Value2':[4,5,6]
                  })

In [121]:
df1

  key  Value1
0   A       1
1   B       2
2   C       3

In [122]:
df2

  key  Value1
0   A       4
1   B       5
2   C       6

In [123]:
pd.merge(df1,df2,on="key",how="inner")

  key  Value1_x  Value1_y
0   A         1         4
1   B         2         5
2   C         3         6

In [124]:
pd.merge(df1,df2,on="key",how="outer")

  key  Value1_x  Value1_y
0   A         1         4
1   B         2         5
2   C         3         6

In [129]:
pd.merge(df1,df2,on="key",how="left")

  key  Value1  Value2
0   A       1     4.0
1   B       2     5.0
2   C       3     NaN

In [130]:
pd.merge(df1,df2,on="key",how="right")

  key  Value1  Value2
0   A     1.0       4
1   B     2.0       5
2   D     NaN       6

In [4]:
import pandas as pd
%pip install openpyxl
df_excel=pd.read_excel('Extracted_Biodata.xlsx')

Requirement already satisfied: openpyxl in c:\mlstart\day2\venv\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\mlstart\day2\venv\lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

In [7]:
df_excel

,Name,Date of Birth,Gotra,Height,Job/Occupation,Education,Work place,Working profile,CTC,Father's Name,Mother's Name,Sisters,Contact Number,Address
0,PAWAN PANDEY,1997-07-08,PARASHAR,5 Feet 6 Inches,Vishwakarma Engineering works,B.A D D U Gorakhpur,Pune,As a forman,3.5 LACS,Mr. Surendra nath pandey,Mrs. Kalawati devi,"Shreya mishra (married), Rinki mishra (married)",9838212604,Vill- Sharangpur Rampur Karkhana Deoria

In [8]:
df_excel.to_pickle('df_excel')
pd.read_pickle('df_excel')

,Name,Date of Birth,Gotra,Height,Job/Occupation,Education,Work place,Working profile,CTC,Father's Name,Mother's Name,Sisters,Contact Number,Address
0,PAWAN PANDEY,1997-07-08,PARASHAR,5 Feet 6 Inches,Vishwakarma Engineering works,B.A D D U Gorakhpur,Pune,As a forman,3.5 LACS,Mr. Surendra nath pandey,Mrs. Kalawati devi,"Shreya mishra (married), Rinki mishra (married)",9838212604,Vill- Sharangpur Rampur Karkhana Deoria